### ISSUE TITLE
Option to hide UI by default

### ISSUE THREAD

**Issue by tanaaKa** [Njpatman/Coalition-Enfusion-UI#26]
We should provide a way to hide all UI elements by default via a toggle-able setting. If enabled, the opacity of all hud elements will be zero and upon holding a specific keybind set by the player, the hud opacity is temporarily set to 1. Once the player lets go of the keybind, the hud opacity should reset back to zero.

**Comment by JessevGool** [comment]
Possibly have to create a custom submenu layout and submenu class
[UI element](https://enfusionengine.com/api/redirect?to=enfusion://ResourceManager/~ArmaReforger:UI/layouts/Menus/SettingsMenu/AudioSettings.layout)

[Menu Script](https://enfusionengine.com/api/redirect?to=enfusion://ResourceManager/~ArmaReforger:scripts/Game/UI/Menu/SettingsMenu/SCR_AudioSettingsSubMenu.c)

[Line 279](https://enfusionengine.com/api/redirect?to=enfusion://ResourceManager/~core:scripts/GameLib/gameLib.c 
)

**Comment by Njpatman** [comment]
Completed in 1.3.0 release
