### ISSUE TITLE
Squad Leaders are not given leader of the squad after briefing

### ISSUE THREAD

**Issue by Salamiboio** [Njpatman/Coalition-Enfusion-UI#50]

**Comment by Njpatman** [comment]
This won't/can't be addressed through CSI, as I can't do anything about it. CSI uses the vanilla group leader value set through the vanilla group manager. There's nothing I can do about Reforger Lobby messing stuff up.

**Comment by tanaaKa** [comment]
It also does it when taking zeus and entering/exiting the interface.

**Comment by Njpatman** [comment]
I will look into that

**Comment by Njpatman** [comment]
Unable to fix, whatever code does the Zeus thing cannot be edited.
